### ISSUE TITLE
dune 2.0.0: promotion stops after first rule failure

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2958]
When shifting RWO [to dune 2.0](https://github.com/realworldocaml/book/pull/3232) and then to [ocaml 4.08](https://github.com/realworldocaml/book/pull/3233), we noticed that `dune build` errors out after failing the first promotion.  Previously, it would continue on until all the promotions were attempted.

This means that we have to iteratively run `dune build` on RWO via `for in in 1 2 3 4 5 6 7 8 9; do dune build || dune promote; done` to get the complete diff.  I believe the dune 1 behaviour is the right one here, since auto-promote also seems to fail with dune 2 in the current state.

**Comment by aalekseyev** [comment]
I'd like to understand this better:
- why does promotion fail?
- why does rerunning it multiple times help?

By reading the promotion code of dune 1.11.4 I can't see how it could proceed after promotion failure.

**Comment by diml** [comment]
My native understanding is that if you have two independent diffs, for instance with the following dag:

```
    o
   / \
  /   \
diff  diff
```

Then dune 1 would systematically report both diffs while dune 2 only reports one of them, and I guess at random. @avsm, is that what you are observing? I can't think of how we would have broken this though.

**Comment by avsm** [comment]
That's indeed what I'm observing @diml -- it eventually hits a fixed point after the set of independent promotions are all complete, but it's a real pain to work with. 

You can try this for yourself with the RWO repository, for example by using 4.09.0 and running the tests (they will result in promotions since the repo is currently for 4.08.1):

```
opam switch create 4.09.1
opam install -y dune
git clone git://github.com/realworldocaml/book
cd book
dune runtest
```

This will result in a promotion failure in the `guided-tour` chapter. Then:

```
dune runtest
```

will result in a promotion failure in the `classes` chapter. And so on through all the chapters.

It might be that this serialisation is due to the use of a `(locks)` directive in the dune files -- I'm not sure.

**Comment by aalekseyev** [comment]
Oh, I get it now! Thanks.

**Comment by diml** [comment]
BTW, @avsm are you sure that it is not just the order of reported error that is different between runs? Right now, it is a known issue that Dune reports errors in a different order. That something we should fix, but it's not a completely trivial fix. Well, we could print all the errors at the end but this is not a great user experience.

**Comment by diml** [comment]
I ran the following in a loop:

```
dune runtest --diff-command 'function x { echo DIFF "$@"; exit 1; }; x'  2>&1 | \
  grep ^DIFF | sort 
```

I'm getting pretty much the same output every times. There are a few differences occasionally, but at the same time the diff produces are not constant either. I remember that @NathanReb told me that there was a bit of non-determinism in mdx, so I'm blaming the few differences I'm seeing on mdx :) And indeed, the line number in the diffs of the same files are not constant between runs.

**Comment by avsm** [comment]
I don't believe the issue is the order of reported errors -- since these are rules that can run in parallel, it's expected that dune has the freedom to evaluate them in any order.  The issue is that in dune1, _all_ the possible parallel promotions ran, but now only one of them seems to happen before stopping the build.

My expectation would be that `dune build --auto-promote` would treat a failed promotion as a success (after promoting the file to the source tree of course) and then continue with the remaining rules. That doesn't seem to happen in the RWO repository, so there's no effective workflow now beyond the `while ; done` wrapper script to evaluate all the chapter files.

**Comment by diml** [comment]
That's reasonable expectation, but not straightforward to implement and that's why it is not the case right now. Basically, when dune promotes a file following a `(diff ...)` action, it might need to rebuild things that have already been built, so we are no longer in a "one walk of the build dag" scenario and we are rather in a self-modifying build scenario.

That definitely wasn't supported in dune 1.

We could change dune to rebuild in a loop until we reach a fix-point, but that's gonna be a bit slow. However, with the work we are currently doing to improve the polling that could be made more efficient.

**Comment by avsm** [comment]
I'm travelling at the moment, but when I get a chance I'll go back to rebuild RWO with dune 1.x to just test that the promotion behaviour was as I describe.  I thought with this issue I was requesting a restoration of old existing functionality in dune 1.x,  but I'm assailed by doubts now :-)

**Comment by avsm** [comment]
I've gone back to dune 1.11.4 to confirm if this behaviour is a change from dune 1->2 or not, and it does appear to be.

```
# with rwo/book@b20002b525807e94d6c84eec2b050f65bd8517a7 and dune 1.11.4
# modified two expect tests to force a promotion
% dune runtest
Done: 21837/21841 (jobs: 1)File "book/guided-tour/README.md", line 1, characters 0-0:
         git (internal) (exit 1)
(cd _build/default && /usr/bin/git diff --no-index --color=always -u book/guided-tour/README.md book/guided-tour/README.md.corrected)
diff --git a/book/guided-tour/README.md b/book/guided-tour/README.md.corrected
index 53e9f670..31d8b3a2 100644
--- a/book/guided-tour/README.md
+++ b/book/guided-tour/README.md.corrected
@@ -109,9 +109,9 @@ the `let` keyword. This is known as a *let binding*:
 
-val x : int = 7
+val x : int = 47
 # let y = x + x
-val y : int = 14
+val y : int = 94
 <...>
val x7 : int = 7
 # let x_plus_y = x + y
-val x_plus_y : int = 21
+val x_plus_y : int = 141
 # let x' = x + 1
-val x' : int = 8
+val x' : int = 48
 
 The following examples, however, are not legal:
Done: 21837/21841 (jobs: 1)
File "book/variables-and-functions/README.md", line 1, characters 0-0:
         git (internal) (exit 1)
(cd _build/default && /usr/bin/git diff --no-index --color=always -u book/variables-and-functions/README.md book/variables-and-functions/README.md.corrected)
diff --git a/book/variables-and-functions/README.md b/book/variables-and-functions/README.md.corrected
index daf4d5ab..1c4579b1 100644
--- a/book/variables-and-functions/README.md
+++ b/book/variables-and-functions/README.md.corrected
@@ -40,11 +40,11 @@ Here's a simple example.
 # open Base
 # let x = 33
-val x : int = 3
+val x : int = 33
 # let y = 4
 val y : int = 4
 # let z = x + y
-val z : int = 7
+val z : int = 37
<...>
```

So my understanding is that this behaviour:
> The issue is that in dune1, all the possible parallel promotions ran, but now only one of them seems to happen before stopping the build.
is indeed a change with dune 2.0.0.

**Comment by jberdine** [comment]
FWIW I have encountered what I think is the same change in behavior but in the context of promoting expect tests. For now I've gone back to 1.11.4.

**Comment by diml** [comment]
Alright, I'm trying to come up with a minimal reproduction case for the testsuite

**Comment by diml** [comment]
I can reproduce @avsm observations, but I didn't yet managed to write a minimal example for the testsuite or bisect dune to find when this regression was introduced. I'm off until the 6th of January, I'll pick up at that point unless someone has a chance to look at this before.

**Comment by NathanReb** [comment]
We use dune `locks` in RWO so that might be part of the issue, I'll give this a try if I get some time!

**Comment by NathanReb** [comment]
I made a MWE here: https://github.com/NathanReb/dune-promotion-stop-example

Running `dune runtest` with dune 1.11 indeed runs both promotions and display all the diffs while doing it with dune 2.0 stops after the first one.

Without the use of the `locks`, both versions run all promotions.

I'll open a PR to add that to the test suite!

**Comment by diml** [comment]
This should be fixed as of Dune 2.1.2

**Comment by jberdine** [comment]
I'm not sure I understand the final state of the expected behavior for this. What I still see with dune 2.2.0 is that in a situation where executing `dune runtest --auto-promote` only promotes one file (maybe target) at a time, requiring a number of repetitions before all the files get promoted. Is this expected?

If it matters, the command is actually `dune build @_build/<context>/runtest @_build/<context>/src/fmt --auto-promote` although the behavior is the same without the `fmt` target. The promotions come from using `ppx_inline_test` with library stanzas containing `(inline_tests)`.

**Comment by diml** [comment]
It is expected to be fixed, i.e. one command should promote everything. Do you a reproduction case we could look at?
