### ISSUE TITLE
Problem while building Dune on macOS

### ISSUE THREAD

**Issue by chanikabla** [ocaml/dune#3925]
Hi

i'm trying to install graphics with ocaml using opam install, but the following command : 

ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml

generates the following error message : 

Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _fdlist_to_fdset in libunix.a(select.o)
      _fdset_to_fdlist in libunix.a(select.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "boot/duneboot.ml", line 1:

Can you help ?

**Comment by nojb** [comment]
Hello, have you been able to solve this problem?

**Comment by nojb** [comment]
No activity on the last few months, assuming issue has been resolved.

**Comment by maroneze** [comment]
I just stumbled upon this problem, updated my macOS Catalina (to 10.15.7), but the problem still happens.

It's happening only on a `system` switch, `ocaml-system.4.12.0`. If I switch to `ocaml-base-compiler.4.12.0`, everything works.

Also, it's not limited to `dune`; it also happens e.g. with `ocamlfind`. It seems that any package which uses `unix.cmxa` triggers this issue.

I'm not very familiar with macOS, but it seems I only have the CommandLineTools installed, not full Xcode. I cannot easily install Xcode from the App Store, because it says that I need "macOS 11.0 or later", but company policy forbids me from upgrading to Big Sur. I found URLs to older versions of Xcode, compatible with Catalina, but they all seem to require an Apple Developer account to allow me to download it, and I do not currently have one.

Anyway, I'm posting this mostly to indicate a possible alternative solution (installing a non-system compiler), since this issue is currently the only Google result for the error message.
