### ISSUE TITLE
[Cache] Cache daemon is not Windows compatible

### ISSUE THREAD

**Issue by smorimoto** [ocaml/dune#4167]
The cache daemon uses `Unix.fork` and is not Windows compatible. It should be easy to fix, but to make sure I don't forget that, I write it down as a quick issue.

**Comment by rgrinberg** [comment]
The direct mode should work on Windows however.

**Comment by smorimoto** [comment]
Yeah, I just skimmed the code, but the direct mode should work.

**Comment by smorimoto** [comment]
Oh, no, the direct mode doesn't seem to work on Windows too.

```
#=== ERROR while compiling re.1.9.0 ===========================================#
# context              2.0.8 | win32/x86_64 | ocaml-variants.4.10.2+mingw64c | git+https://github.com/fdopen/opam-repository-mingw.git#opam2
# path                 ~/.opam/ocaml-variants.4.10.2+mingw64c/.opam-switch/build/re.1.9.0
# command              C:\Users\runneradmin\.opam\ocaml-variants.4.10.2+mingw64c\bin\dune.exe build -p re -j 4
# exit-code            1
# env-file             ~/.opam/log/re-6536-a5b00a.env
# output-file          ~/.opam/log/re-6536-a5b00a.out
### output ###
# Error: utimes: C:\Users\runneradmin\Local Settings\Cache\dune\db\beacon: The
# operation completed successfully.
# 
```

**Comment by rgrinberg** [comment]
> ### output ###
> # Error: utimes: C:\Users\runneradmin\Local Settings\Cache\dune\db\beacon: The
> # operation completed successfully.

Most bizarre error message. There's an error, but the message indicates success?!

cc @dra27 @tmattio who perhaps have more experience `Unix.utimes` on Windows.

**Comment by dra27** [comment]
The error message comes from `Unix.(error_message (EUNKNOWNERR 0))` and is the string representation of `ERROR_SUCCESS`. I couldn't see a single point in the Dune sources to improve the error message, but what's happened is equivalent to displaying `errno` but finding it's `0`.

**Comment by smorimoto** [comment]
@dra27 -sensei always works incredibly efficiently...

**Comment by rgrinberg** [comment]
Fixed in 2.8.3

**Comment by smorimoto** [comment]
I don't think this should be closed because daemon is still not working. Only direct mode now works.

**Comment by rgrinberg** [comment]
Indeed. Let’s keep it open until we fix the other modes as well.

**Comment by smorimoto** [comment]
We've made some progress in the direct mode, but I'm seeing another strange problem that only occurs on Windows.

https://github.com/ocsigen/js_of_ocaml/pull/1089/checks?check_run_id=2159269998#step:8:321

```
#=== ERROR while compiling uri.4.1.0 ==========================================#
# context     2.0.8 | win32/x86_64 | ocaml-variants.4.12.0+mingw64c | git+https://github.com/fdopen/opam-repository-mingw.git#opam2
# path        ~/.opam/ocaml-variants.4.12.0+mingw64c/.opam-switch/build/uri.4.1.0
# command     C:\Users\runneradmin\.opam\ocaml-variants.4.12.0+mingw64c\bin\dune.exe build -p uri -j 2
# exit-code   1
# env-file    ~/.opam/log/uri-4800-0543f2.env
# output-file ~/.opam/log/uri-4800-0543f2.out
### output ###
# Error: unlink: C:\Users\runneradmin\Local
# Settings\Cache\dune\db\promoting.641381.188\data: Permission denied


#=== ERROR while compiling ppxlib.0.22.0 ======================================#
# context     2.0.8 | win32/x86_64 | ocaml-variants.4.12.0+mingw64c | git+https://github.com/fdopen/opam-repository-mingw.git#opam2
# path        ~/.opam/ocaml-variants.4.12.0+mingw64c/.opam-switch/build/ppxlib.0.22.0
# command     C:\Users\runneradmin\.opam\ocaml-variants.4.12.0+mingw64c\bin\dune.exe build -p ppxlib -j 2 @install
# exit-code   1
# env-file    ~/.opam/log/ppxlib-4800-4c6492.env
# output-file ~/.opam/log/ppxlib-4800-4c6492.out
### output ###
# Error: unlink: C:\Users\runneradmin\Local
# Settings\Cache\dune\db\promoting.ae8efc.180\data: Permission denied
```

**Comment by rgrinberg** [comment]
What about other packages? Say `angstrom` for example, did it build successfully?

I'm not sure why there's no permissions. The directory is being created by dune inside a location which should be writeable. 

```
        Temp.temp_in_dir ~perms:0o700 Temp.Dir ~dir:root ~prefix:"promoting."
          ~suffix:("." ^ string_of_int (Unix.getpid ()))
```

Perhaps @snowleopard or @dra27 might know?

**Comment by smorimoto** [comment]
Yeah, this is strange. To avoid such problems, actions-ml automatically overrides the permissions every time on Windows.

```
C:\windows\system32\fsutil.exe behavior query SymlinkEvaluation
  Local to local symbolic links are enabled.
  Local to remote symbolic links are enabled.
  Remote to local symbolic links are disabled.
  Remote to remote symbolic links are disabled.

C:\windows\system32\fsutil.exe behavior set symlinkEvaluation R2L:1 R2R:1

C:\windows\system32\fsutil.exe behavior query SymlinkEvaluation
  Local to local symbolic links are enabled.
  Local to remote symbolic links are enabled.
  Remote to local symbolic links are enabled.
  Remote to remote symbolic links are enabled.
```

**Comment by smorimoto** [comment]
I just tried to install angstrom, and it works as expected!

**Comment by dra27** [comment]
I have a suspicion about what this might be, but I'm a bit pressed for time (as ever!). Please could I have a clear repro case - ideally a Dune invocation, but an opam one will do which repeatably shows this failure?

**Comment by smorimoto** [comment]
I will create a repro case after I get home.

**Comment by smorimoto** [comment]
I made the smallest repro case here:
https://github.com/smorimoto/ocaml-dune-repro-4167/runs/2171704001?check_suite_focus=true

**Comment by dra27** [comment]
Thanks, @smorimoto! I was able to take that and reduce it to a direct build of ocaml-uri with Dune. It's repeatable which is handy. I'm very puzzled as to why you're messing around with `fsutil` at all - what's that meant to be fixing? (in particular, I think the workflow you point to includes that change, but still breaks).

The issue is a race condition - I've had a brief exchange with @snowleopard and we're suspicious of:
https://github.com/ocaml/dune/blob/5326730ba57b15c4d0d0776ef7de0769948ab0e4/src/cache/local.ml#L238-L278

The file `data` is created by multiple processes. Using a process-specific value (or, as I did, `"data" ^ string_of_int (Random.int 65536)`!) eliminates the problem, but a better fix should be sought.

The `unlink` exception is almost certainly a consistent attempt to delete a file which is being written - in the ocaml-uri case, it's an executable being cached so on Windows it will be big and probably triggers Defender so there's a big enough delay to see the race on the time. On Unix, I expect it's causing cache misses?

**Comment by snowleopard** [comment]
Thanks for the investigation @dra27! I self-assigned to fix the race, hopefully, I'll get to it soon. 

@smorimoto Could you confirm if using the `Random.int` trick solves the issue for you?

**Comment by smorimoto** [comment]
@snowleopard That works:
https://github.com/smorimoto/ocaml-dune-repro-4167/runs/2174690105

**Comment by smorimoto** [comment]
@dra27 Although fsutil is mainly set for Cygwin, it has nothing to do with this caching problem!

**Comment by snowleopard** [comment]
> @snowleopard That works:
> https://github.com/smorimoto/ocaml-dune-repro-4167/runs/2174690105

@smorimoto That's great, thank you for confirming.

**Comment by dra27** [comment]
> @dra27 Although fsutil is mainly set for Cygwin, it has nothing to do with this caching problem!

What's it being used for on Cygwin?

**Comment by smorimoto** [comment]
IIRC, it was necessary for `winsymlinks:native`.
https://sourceware.org/legacy-ml/cygwin/2013-05/msg00405.html

**Comment by snowleopard** [comment]
@smorimoto I've fixed the race in #4406. It would be very helpful if you could confirm if the main branch works for you.

**Comment by smorimoto** [comment]
@snowleopard That was very fast work! and the PR fixed the bug as expected: https://github.com/smorimoto/ocaml-dune-repro-4167/runs/2209405229

**Comment by snowleopard** [comment]
@smorimoto Thank you, happy to see the fix worked!

Do we need to fix anything else in the cache daemon on Windows, or can this issue be now closed?

**Comment by dra27** [comment]
I'm not sure that @fpottier's was intended to close this?!

**Comment by smorimoto** [comment]
Definitely not! Due to strange specs of GitHub, an incorrect close occurs! 🤣

**Comment by snowleopard** [comment]
By the way, we've recently completely rewritten the implementation of the shared cache in Dune. In particular, there is no cache daemon anymore. It is still worth testing the new implementation on Windows, of course.

The docs for the new shared cache can be found here: https://github.com/ocaml/dune/blob/main/doc/caching.rst.

(For some reason, the docs [here](https://dune.readthedocs.io/en/latest/caching.html) haven't been regenerated yet.)

**Comment by smorimoto** [comment]
Oh, then we can close this. Are changes such as cache going to be released as dune 3?

**Comment by snowleopard** [comment]
> Are changes such as cache going to be released as dune 3?

Yes, that's right.

**Comment by smorimoto** [comment]
I can't wait for dune 3! Thank you for a lot of your efforts on this.

**Comment by snowleopard** [comment]
@smorimoto We're looking forward to Dune 3 too! Thanks for your help with testing Dune cache on Windows.
