### ISSUE TITLE
Meta Generation Bug (beta 17 regression)

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#440]
The change to remove the generation of transitive dependency in the META has brought on the unintended consequence of removing the ppx_runtime_deps of every library that isn't a rewriter or deriver. Unfortunately, this is still not enough for the ppx compatibility layer because it doesn't respect the `ppx_runtime_deps` variable in the first place. For the compatibility layer, we will have to go back and generate the transitive closure in the META.

**Comment by diml** [comment]
Both problems should be fixed by #441

**Comment by rgrinberg** [comment]
Looks like this is still an issue:

```
- Error: No implementations provided for the following modules:
-          Ppx_compare_lib referenced from /home/opam/.opam/4.05.0/lib/ppx_expect/common/expect_test_common.cmxa(Expect_test_common__File)
```

from: https://github.com/ocaml/dune/issues/440

**Comment by rgrinberg** [comment]
Another issue detected: A generated META file doesn't reflect the requires added as the result of preprocessing it with a ppx. Will add a test case shortly.

**Comment by rgrinberg** [comment]
@diml fixed this conclusively.
