### ISSUE TITLE
Error messages are sometimes not displayed

### ISSUE THREAD

**Issue by esope** [ocaml/dune#6115]
Sometimes, error messages are not displayed at all when `dune` is run from a terminal.
If you redirect `stderr` to a file, however, then the error messages are correctly written to that file.
This bug seems to happen on the dev version of `dune` only.
I was not able to create a test that witnesses this behavior: tests seem to redirect `stderr`.

## Expected Behavior
Whether `stderr` is redirected or not, the same error messages should be produced (with the exception of styles and colors, maybe).

## Actual Behavior
It happens sometimes that `dune command args` produces no visible error messages, but `dune command args 2> errors.txt` writes some error messages to the file `errors.txt`.

## Reproduction

`dune describe bug` displays no message at all.

`dune describe bug 2> errors.txt` writes the error message `Error: Unknown constructor bug` to `errors.txt` as expected.

## Specifications

- Version of `dune`: dev version, with git hash `87bc1bfa16136a9f8833e236c23b8454a309e55e`
- Version of `ocaml`: 4.14.0
- Operating system (distribution and version): Linuxmint 21

**Comment by emillon** [comment]
I've seen that too, I'll investigate

**Comment by emillon** [comment]
That has been introduced in #6068

**Comment by emillon** [comment]
@rgrinberg it's probably more efficient if you have a look at this one - looks like we're missing a flush on stderr at the end.

**Comment by rgrinberg** [comment]
Np. Should be simple enough to fix. I'll manually shut down the UI thread once the Term.t finishes executing.

**Comment by esope** [comment]
Fixed by #6119

**Comment by gridbugs** [comment]
Heads up that I'm still encountering this while building dune on an M1 Mac.

**Comment by gridbugs** [comment]
I see this on both macOS and dockerized ubuntu, and I see it when I build non-dune projects as long as I'm using a dune which I build from source. I don't see this error using 3.6.1 installed from opam.

**Comment by gridbugs** [comment]
Bisected and the problem was introduced in this commit 1f518fb5c20869b17e99b50097f9bb4ea5f5e79c

**Comment by gridbugs** [comment]
This seems to fix the problem:
```diff
diff --git a/src/dune_console/dune_console.ml b/src/dune_console/dune_console.ml
index f233e4637..22aab51fb 100644
--- a/src/dune_console/dune_console.ml
+++ b/src/dune_console/dune_console.ml
@@ -304,9 +304,9 @@ module Backend = struct
         Base.start ();
         while true do
           Mutex.lock mutex;
+          Base.render state;
           let finish_requested = state.finish_requested in
           if finish_requested then raise_notrace Exit;
-          Base.render state;
           Mutex.unlock mutex;
           let now = Unix.gettimeofday () in
           let elapsed = now -. !last in
```

**Comment by esope** [comment]
@rgrinberg @Alizter it seems that https://github.com/ocaml/dune/commit/1f518fb5c20869b17e99b50097f9bb4ea5f5e79c is your commit.
Do you want to have a look at this issue?

**Comment by Alizter** [comment]
@esope that commit has since been reverted.

**Comment by esope** [comment]
Oh, OK. My bad.
@gridbugs do you still observe the bug with a dune version close to tip?

**Comment by gridbugs** [comment]
I no longer observe the bug on tip (715825e0b)

**Comment by esope** [comment]
Great. I am closing the issue, then. Do not hesitate to reopen it if necessary.
